# Generated by Django 3.2.4 on 2021-06-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_website', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slider1', models.ImageField(default='static/default.jpg', upload_to='static/slider_image/')),
                ('Slider2', models.ImageField(default='static/default.jpg', upload_to='static/slider_image/')),
                ('Slider3', models.ImageField(default='static/default.jpg', upload_to='static/slider_image/')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.websitename')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_nav_item', models.CharField(max_length=500)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.websitename')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='static/default.jpg', upload_to='static/images/')),
                ('image2', models.ImageField(default='static/default.jpg', upload_to='static/images/')),
                ('image3', models.ImageField(default='static/default.jpg', upload_to='static/images/')),
                ('image4', models.ImageField(default='static/default.jpg', upload_to='static/images/')),
                ('image5', models.ImageField(default='static/default.jpg', upload_to='static/images/')),
                ('image6', models.ImageField(default='static/default.jpg', upload_to='static/images/')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.websitename')),
            ],
        ),
    ]
