# Generated by Django 3.2.4 on 2021-06-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.ImageField(default='static/default.jpg', upload_to='static/footer_images/')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.websitename')),
            ],
        ),
    ]
